### ISSUE TITLE
Undefined reference to checkMemory

### ISSUE THREAD

**Issue by JWJ212** [MrGilli/Quplexity#1]
Let me preface this by saying I know nothing about QC or C++.

With that out of the way when trying to run the program on my setup
(Ryzen 9 7940HS, Fedora 39, Hyprland, Kitty terminal emulator, 32 gigs of ram)
I am met with

 `main.cpp:(.text+0x23e): undefined reference to checkMemory()`

When trying to poke around the project I found where the function is called in main.cpp but not defined (as the error code suggests)
It returns a second error relating to there not being a qcvm directory (which appears to be a direct result of the previous failure)

I would be willing to learn the concepts necessary to help with this project as well as it seems very fun, but for now this is the limit of my ability.

**Comment by MrGilli** [comment]
I'm sorry for the inconvenience, errors should be fixed in the version that I'm about to upload maybe you could try again. 
I would love some help with the project, if you want to discuss more you can email me here: jacobygill@outlook.com or on discord @mrgill0651.
